#!/usr/bin/python3


CHRONY_KEYS_PATH = '/etc/chrony/chrony.keys'


def render_config(config):
    lines = [
        '# Generated by AWG Manager. Manual edits may be overwritten.',
    ]
    warnings = []

    if _enabled_keys(config):
        lines.append(f'keyfile {CHRONY_KEYS_PATH}')

    if config['time']['ntp_enabled']:
        for source in config['sources']:
            if not source['enabled']:
                continue
            parts = [
                source['type'],
                source['address'],
            ]
            if source['iburst']:
                parts.append('iburst')
            parts.extend(['minpoll', str(source['min_poll']), 'maxpoll', str(source['max_poll'])])
            if source['auth_key'] not in ('', 'none'):
                parts.extend(['key', source['auth_key']])
            if source['options']:
                parts.append(source['options'])
            lines.append(' '.join(parts))
        lines.append('makestep 1.0 3')

    server = config['server']
    if server['enabled']:
        lines.append(f"port {server['listen_port']}")
        if server['bind_address']:
            lines.append(f"bindaddress {server['bind_address']}")
        if server['bind_interface']:
            lines.append(f"binddevice {server['bind_interface']}")
        if server['use_local_clock']:
            local_line = f"local stratum {server['local_stratum']}"
            if server['orphan_mode']:
                local_line += ' orphan'
            lines.append(local_line)
        if server['rate_limit_enabled']:
            lines.append(f"ratelimit interval {server['rate_interval']} burst {server['rate_burst']}")

    lines.append(f"clientloglimit {server['client_log_limit']}")

    for rule in config['access']:
        if rule['enabled']:
            lines.append(f"{rule['action']} {rule['network']}")

    lines.append('driftfile /var/lib/chrony/chrony.drift')
    if config['time']['rtcsync']:
        lines.append('rtcsync')
    lines.extend([
        'logdir /var/log/chrony',
        'minsources 1',
    ])
    return {'content': '\n'.join(lines) + '\n', 'warnings': warnings}


def render_keys(config):
    lines = [
        f"{item['id']} {item['algorithm']} {item['secret']}"
        for item in config.get('keys', [])
        if item.get('enabled')
    ]
    return '\n'.join(lines) + ('\n' if lines else '')


def _enabled_keys(config):
    return [item for item in config.get('keys', []) if item.get('enabled')]
