#!/usr/bin/python3
import subprocess
import sqlite3
import ipaddress
import getpass
import base64
import sys
import os
import random
import tempfile
import io
from cryptography.fernet import Fernet
import segno


def derive_encryption_key(raw_key):
    key_bytes = raw_key.encode('utf-8')
    return base64.urlsafe_b64encode(key_bytes + b'\0' * (32 - len(key_bytes))).decode('utf-8')


def get_argument_value(flag_name, default=None):
    if flag_name in sys.argv:
        flag_index = sys.argv.index(flag_name)
        if flag_index + 1 < len(sys.argv):
            return sys.argv[flag_index + 1]
    return default


def load_encryption_secret():
    encryption_key_path = get_argument_value('-r')
    if encryption_key_path is not None:
        with open(str(encryption_key_path), "r") as encryption_key_file:
            return encryption_key_file.read().rstrip('\n')
    print("*** Введите ключ шифрования приватного ключа клиента ***")
    return getpass.getpass("Введите ключ: ").rstrip('\n')


encryption_secret = load_encryption_secret()
encryption_key = derive_encryption_key(encryption_secret)




#_path = os.path.dirname(os.path.abspath(__file__))

# Получить путь к символической ссылке
#link_path = os.path.abspath(__file__)

# Разрешить символическую ссылку и получить путь к оригинальному файлу
#org_path = os.path.dirname(os.path.realpath(link_path))

# Сменить каталог
#os.chdir(org_path)



bd_path = '/etc/wg-manager'
API_KEY_ENV_VAR = 'AWG_MANAGER_API_KEY'
API_KEY_FILE = os.path.join(bd_path, 'api.key')
if os.path.isdir(bd_path):
    # Подключение к базе данных
    conn = sqlite3.connect(bd_path+"/"+"clients.db")
else:
    print('Directory does not exist')
    os.system("mkdir "+bd_path)
    conn = sqlite3.connect(bd_path+"/"+"clients.db")



c = conn.cursor()

# Создание таблицы clients
c.execute('''CREATE TABLE IF NOT EXISTS clients (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                pubkey TEXT NOT NULL,
                privkey TEXT NOT NULL,
                ip TEXT NOT NULL,
                wg_interface TEXT NOT NULL
            )''')

# Создание таблицы wg_interfaces
c.execute('''CREATE TABLE IF NOT EXISTS wg_interfaces (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                wg_interface TEXT NOT NULL,
                awg_version TEXT NOT NULL DEFAULT '1',
                port_number INTEGER NOT NULL,
                wg_ip_addr TEXT NOT NULL,
                wg_ip_cidr INTEGER NOT NULL,
                private_key TEXT NOT NULL,
                pubkey TEXT NOT NULL,
                srv_ip TEXT NOT NULL,
                srv_dns TEXT NOT NULL,
                Jc INTEGER,
                Jmin INTEGER,
                Jmax INTEGER,
                S1 INTEGER,
                S2 INTEGER,
                S3 INTEGER,
                S4 INTEGER,
                H1 TEXT,
                H2 TEXT,
                H3 TEXT,
                H4 TEXT,
                I1 TEXT,
                I2 TEXT,
                I3 TEXT,
                I4 TEXT,
                I5 TEXT
            )''')


def ensure_wg_interfaces_schema():
    expected_columns = {
        'Jc': 'INTEGER',
        'Jmin': 'INTEGER',
        'Jmax': 'INTEGER',
        'awg_version': "TEXT NOT NULL DEFAULT '1'",
        'S1': 'INTEGER',
        'S2': 'INTEGER',
        'S3': 'INTEGER',
        'S4': 'INTEGER',
        'H1': 'TEXT',
        'H2': 'TEXT',
        'H3': 'TEXT',
        'H4': 'TEXT',
        'I1': 'TEXT',
        'I2': 'TEXT',
        'I3': 'TEXT',
        'I4': 'TEXT',
        'I5': 'TEXT',
    }
    existing_columns = {
        row[1] for row in c.execute("PRAGMA table_info(wg_interfaces)").fetchall()
    }
    for column_name, column_type in expected_columns.items():
        if column_name not in existing_columns:
            c.execute(
                f'ALTER TABLE wg_interfaces ADD COLUMN {column_name} {column_type}'
            )


ensure_wg_interfaces_schema()

# Сохраняем изменения и закрываем подключение
conn.commit()


WG_INTERFACE_COLUMNS = (
    'id, wg_interface, awg_version, port_number, wg_ip_addr, wg_ip_cidr, private_key, pubkey, '
    'srv_ip, srv_dns, Jc, Jmin, Jmax, S1, S2, S3, S4, H1, H2, H3, H4, I1, I2, I3, I4, I5'
)


def normalize_config_value(value):
    if value is None:
        return None
    if isinstance(value, bytes):
        value = value.decode('utf-8')
    value = str(value).strip()
    return value if value else None


def load_api_key():
    env_api_key = normalize_config_value(os.environ.get(API_KEY_ENV_VAR))
    if env_api_key is not None:
        return env_api_key
    if os.path.isfile(API_KEY_FILE):
        with open(API_KEY_FILE, 'r') as api_key_file:
            return normalize_config_value(api_key_file.read())
    return None


def save_api_key(api_key):
    normalized_api_key = normalize_config_value(api_key)
    if normalized_api_key is None:
        raise ValueError('API key is empty')
    with open(API_KEY_FILE, 'w') as api_key_file:
        api_key_file.write(normalized_api_key + '\n')
    os.chmod(API_KEY_FILE, 0o600)


def render_qr_in_terminal(content):
    qr_code = segno.make(content)
    qr_code.terminal(compact=True)


def build_qr_svg(content):
    qr_code = segno.make(content)
    output = io.BytesIO()
    qr_code.save(output, kind='svg', scale=4)
    return output.getvalue()


def verify_api_auth(api_key, provided_encryption_secret):
    saved_api_key = load_api_key()
    if saved_api_key is None:
        return False, 'API key is not configured'
    if normalize_config_value(api_key) != saved_api_key:
        return False, 'Invalid API key'
    if normalize_config_value(provided_encryption_secret) != encryption_secret:
        return False, 'Invalid encryption key'
    return True, None


def generate_awg_obfuscation_params():
    jc = random.randint(4, 12)
    jmin = 8
    jmax = 80
    s1 = random.randint(15, 150)
    s2 = random.randint(15, 150)
    while s1 + 56 == s2:
        s2 = random.randint(15, 150)
    s3 = random.randint(15, 150)
    s4 = random.randint(5, 32)

    h_values = random.sample(range(5, 2147483648), 4)
    h1, h2, h3, h4 = [str(value) for value in h_values]

    return {
        'Jc': jc,
        'Jmin': jmin,
        'Jmax': jmax,
        'S1': s1,
        'S2': s2,
        'S3': s3,
        'S4': s4,
        'H1': h1,
        'H2': h2,
        'H3': h3,
        'H4': h4,
        'I1': None,
        'I2': None,
        'I3': None,
        'I4': None,
        'I5': None,
    }


def get_awg_param_keys_for_version(awg_version):
    awg_version = detect_awg_version(awg_version, {})
    keys = ['Jc', 'Jmin', 'Jmax', 'S1', 'S2', 'H1', 'H2', 'H3', 'H4']
    if awg_version == '2':
        keys.extend(['S3', 'S4', 'I1', 'I2', 'I3', 'I4', 'I5'])
    return keys


def detect_awg_version(awg_version, awg_params):
    normalized_version = normalize_config_value(awg_version)
    if normalized_version in ('1', '2'):
        return normalized_version
    if normalized_version in ('1.0', '1.5'):
        return '1'
    if normalized_version in ('2.0',):
        return '2'

    if any(normalize_config_value(awg_params.get(key)) is not None for key in ('I1', 'I2', 'I3', 'I4', 'I5', 'S3', 'S4')):
        return '2'
    if any(normalize_config_value(awg_params.get(key)) is not None for key in ('Jc', 'Jmin', 'Jmax', 'S1', 'S2', 'H1', 'H2', 'H3', 'H4')):
        return '1'
    return '1'


def build_awg_params_from_row(row):
    return {
        'Jc': row[10],
        'Jmin': row[11],
        'Jmax': row[12],
        'S1': row[13],
        'S2': row[14],
        'S3': row[15],
        'S4': row[16],
        'H1': row[17],
        'H2': row[18],
        'H3': row[19],
        'H4': row[20],
        'I1'