import type { FirewallRule } from '../api'

export type PolicyRuleFamily = 'bridge' | 'netdev'

const defaultBridgeRule: Partial<FirewallRule> = {
  family: 'bridge',
  table: '',
  chain: 'forward',
  action: 'accept',
  proto: null,
  sport: null,
  dport: null,
  ct_state: null,
  meta_pkttype: null,
  meta_iifgroup: null,
  meta_oifgroup: null,
  mark_match: null,
  ct_mark_match: null,
  fib_check: null,
  socket_match: null,
  rt_nexthop: null,
  ipv6_exthdrs: null,
  enabled: true,
  comment: '',
  ibrname: null,
  obrname: null,
  ether_src: null,
  ether_dst: null,
  ether_type: null,
  vlan_id: null,
  ct_helper_set: null,
  ct_timeout_set: null,
  ct_expectation_set: null,
  limit_rate: null,
  counter_name: null,
  limit_name: null,
  quota_name: null,
  queue_num: null,
  queue_flags: null,
  dup_to: null,
  dup_dev: null,
  fwd_to: null,
  fwd_dev: null,
  fwd_family: null,
  counter: false,
  log_prefix: null,
  log_level: null,
  log_flags: null,
  log_group: null,
  log_snaplen: null,
  log_queue_threshold: null,
  target_chain: null,
  reject_type: null,
}

const defaultNetdevRule: Partial<FirewallRule> = {
  family: 'netdev',
  table: '',
  chain: 'ingress',
  action: 'accept',
  proto: null,
  src: null,
  dst: null,
  in_interface: null,
  sport: null,
  dport: null,
  ct_state: null,
  meta_pkttype: null,
  meta_iiftype: null,
  meta_iifgroup: null,
  mark_match: null,
  ct_mark_match: null,
  ether_src: null,
  ether_dst: null,
  ether_type: null,
  vlan_id: null,
  limit_rate: null,
  queue_num: null,
  queue_flags: null,
  fwd_to: null,
  fwd_dev: null,
  fwd_family: null,
  counter: false,
  log_prefix: null,
  log_level: null,
  log_flags: null,
  log_group: null,
  log_snaplen: null,
  log_queue_threshold: null,
  target_chain: null,
  enabled: true,
  comment: '',
}

export function getDefaultPolicyRuleForm(family: PolicyRuleFamily): Partial<FirewallRule> {
  return family === 'netdev' ? { ...defaultNetdevRule } : { ...defaultBridgeRule }
}

export function buildPolicyRuleCreateForm(
  family: string,
  table: string,
  chain: string,
  prefill?: Partial<FirewallRule>,
): Partial<FirewallRule> {
  const normalizedFamily: PolicyRuleFamily = family === 'netdev' ? 'netdev' : 'bridge'
  return {
    ...getDefaultPolicyRuleForm(normalizedFamily),
    family: normalizedFamily,
    table,
    chain,
    ...(prefill || {}),
  }
}

export function buildPolicyRuleEditForm(
  rule: FirewallRule,
  fallbackFamily: string,
): Partial<FirewallRule> {
  const normalizedFallback: PolicyRuleFamily = fallbackFamily === 'netdev' ? 'netdev' : 'bridge'
  const normalizedRuleFamily: PolicyRuleFamily = rule.family === 'netdev' ? 'netdev' : 'bridge'
  return {
    id: rule.id,
    family: normalizedRuleFamily || normalizedFallback,
    table: rule.table,
    chain: rule.chain,
    action: rule.action,
    proto: rule.proto || null,
    src: rule.src || null,
    dst: rule.dst || null,
    in_interface: rule.in_interface || null,
    out_interface: rule.out_interface || null,
    sport: rule.sport || null,
    dport: rule.dport || null,
    ct_state: rule.ct_state || null,
    meta_pkttype: rule.meta_pkttype || null,
    meta_iiftype: rule.meta_iiftype || null,
    meta_iifgroup: rule.meta_iifgroup || null,
    meta_oifgroup: rule.meta_oifgroup || null,
    mark_match: rule.mark_match || null,
    ct_mark_match: rule.ct_mark_match || null,
    fib_check: rule.fib_check || null,
    socket_match: rule.socket_match || null,
    rt_nexthop: rule.rt_nexthop || null,
    ipv6_exthdrs: rule.ipv6_exthdrs || null,
    enabled: rule.enabled,
    comment: rule.comment || null,
    ibrname: rule.ibrname || null,
    obrname: rule.obrname || null,
    ether_src: rule.ether_src || null,
    ether_dst: rule.ether_dst || null,
    ether_type: rule.ether_type || null,
    vlan_id: rule.vlan_id || null,
    counter: !!rule.counter,
    log_prefix: rule.log_prefix || null,
    log_level: rule.log_level || null,
    log_flags: Array.isArray(rule.log_flags) ? rule.log_flags : (rule.log_flags ? [String(rule.log_flags) as any] : null),
    log_group: rule.log_group ?? null,
    log_snaplen: rule.log_snaplen ?? null,
    log_queue_threshold: rule.log_queue_threshold ?? null,
    ct_helper_set: rule.ct_helper_set || null,
    ct_timeout_set: rule.ct_timeout_set || null,
    ct_expectation_set: null,
    limit_rate: rule.limit_rate || null,
    counter_name: rule.counter_name || null,
    limit_name: rule.limit_name || null,
    quota_name: rule.quota_name || null,
    queue_num: rule.queue_num || null,
    queue_flags: Array.isArray(rule.queue_flags) ? rule.queue_flags : (rule.queue_flags ? [String(rule.queue_flags) as any] : null),
    dup_to: rule.dup_to || null,
    dup_dev: rule.dup_dev || null,
    fwd_to: rule.fwd_to || null,
    fwd_dev: rule.fwd_dev || null,
    fwd_family: rule.fwd_family || null,
    target_chain: rule.target_chain || null,
    reject_type: rule.reject_type || null,
  }
}
